#! /usr/bin/env ruby

# Auth API setting
Eventaskbot::Api::Auth.configure do |c|
# Auth API add setting
# example
# c.get_oauth_token = {
#    :service => {
#       :yammer => {
#         :user => "your login name",
#         :pass => "your login pass"
#       }
#     }
# }
end

# File API setting
Eventaskbot::Api::File.configure do |c|
# File/Init API settings
# example
# c.init = {
#   :force_update => false, # force create EventaskbotFile
# }
end

# Collector API setting
Eventaskbot::Api::Collector.configure do |c|
# Collector API add setting
# example
# c.in_group = {:service => :yammer, :redmine}
end

Eventaskbot.configure do |c|
  c.plugin_dir = "plugins/"
  c.service = {:yammer => {}}
end
